spring.application.name=leave-management-system

server.port=9090

spring.mongodb.uri=mongodb+srv://rishusingh417:Zf6iKHfD0hToeJcD@cluster0.hydv8fe.mongodb.net/Leave-Management-System?appName=Cluster0